name: my calling workflow
on: push

jobs:
  main_workflow_job:
    uses: maheshkamthe/called-workflow/.github/workflows/my-called-workflow.yml@main
    with:
        first-name: Mahesh
    secrets: inherit



